sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_A498_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_A498_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_A498_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_ACHN_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_ACHN_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_ACHN_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_A549_ATCC_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_A549_ATCC_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_A549_ATCC_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_CAKI_1_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_CAKI_1_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_CAKI_1_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_DLD_1_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_DLD_1_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_DLD_1_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_CCRF_CEM_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_CCRF_CEM_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_CCRF_CEM_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_786_0_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_786_0_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_786_0_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_DMS_114_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_DMS_114_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_DMS_114_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_BT_549_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_BT_549_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_BT_549_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_COLO_205_Default__-ts_2000_-model_gcn_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_COLO_205_Default__-ts_2000_-model_gsage_-lr_1.5e-05.sh
sbatch /home/XXXXX/neuralogic/experiments/dgl/scripts/jair_first10_mol2types_gnnlrnn_COLO_205_Default__-ts_2000_-model_gin_-lr_1.5e-05.sh
