sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_A498_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_A498_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_A498_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_ACHN_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_ACHN_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_ACHN_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_A549_ATCC_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_A549_ATCC_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_A549_ATCC_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_CAKI_1_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_CAKI_1_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_CAKI_1_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_DLD_1_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_DLD_1_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_DLD_1_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_CCRF_CEM_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_CCRF_CEM_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_CCRF_CEM_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_786_0_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_786_0_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_786_0_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_DMS_114_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_DMS_114_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_DMS_114_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_BT_549_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_BT_549_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_BT_549_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_COLO_205_molecules_gnns_gcn.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_COLO_205_molecules_gnns_gin.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
sbatch /home/XXXXX/neuralogic/experiments/java/scripts/jair_first10_mol2types_gnnlrnn_COLO_205_molecules_gnns_gsage.txt__-ts_2000_-fp_fold_-init_glorot_-lr_1.5e-05_-ef_XEnt.sh
